### PR TITLE
Removing forOf in favor of downlevelIteration

### LINKED ISSUE #109: Use of downlevelIteration
**Enhancement**

We should consider using the compiler flag `downlevelIteration`.  Our Symbol shim should be sufficient to allow TypeScript to down emit `for ... of` structures on any iterators.  This means that we would not have to use the "iterator/forOf" function to replicate iteration and more widely adopt iterables throughout the code base (as well as allow downstream authoring with iterables).

### PR DESCRIPTION
**Pull request by rorticus**
**Type:** feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

**Description:**

Using the `downlevelIteration` flag to get rid of the `forOf` function and just use the `for...of` construct instead! Note that this is a breaking change for anything that used `forOf`.

Resolves #109

### CODE REVIEW

**Comment by agubler** [comment]
Do you think we should remove `forOf` and associated functions as part of the initial changes? This will break all downstream projects that use `forOf`, might be best to start converting to using `for (const value of iterable) {` for all dojo 2 packages and then remove them in a later change?

**Comment by dylans** [comment]
> might be best to start converting to using for (const value of iterable) { for all dojo 2 packages and then remove them in a later change

I agree that removing `forOf` later will probably cause us less pain across packages and examples (even though deprecation and remove later is more of a pain).

**Comment by kitsonk** [comment]
Downstream adoption is likely very limited (it is very limited in our packages as it stands).  It is going to be a breaking change no matter what.  I would rather just take the hit now, instead of a long tail of pain of removing something _later_.  Moving global was far more impactful.

**Comment by agubler** [comment]
it's best practice to effectively deprecate an API for a release and then subsequently remove it. I appreciate that adoption may be low, perhaps good to get into practice?

If consensus is to consciously break downstream packages (I don't know how many that actually is!) that depend on the removed functionality on this occasion then the PR is fine as it is.

**Comment by kitsonk** [comment]
We have plenty of practice deprecating APIs.  We even have a API for deprecating our APIs, of course it is in dojo/core and not shim, which is why I actually was hesitant, because we have no concise way, except maybe replicate the deprecation API to shim, which started to feel silly.  Then I thought we would be being dogmatic for dogmatic purposes, because the "remove it" would be during the next major release, of something we have in beta.  We weren't going to wait until Dojo 3 to remove it, so then the question was "in what release do we remove it?"  Again, I assessed the collateral damage to be low (unlike the deprecations in widget core and the moving of global).

I would rather be pragmatic than dogmatic.  There is no universal rule for introducing breaking changes.

**Comment by agubler** [comment]
@kitsonk At the very least, shouldn't we update all affected downstream dojo 2 dependencies to use `for of` syntax before this is merged?

Pragmatic is fine, but I don't think we should break stuff for sakes sake.

**Comment by agubler** [comment]
But you are right the impact seems very low for our internal packages so `¯\_(ツ)_/¯` 😄

**Comment by kitsonk** [comment]
Yes, just to be clear, I expected @rorticus to stage changes for all our packages and convert them to have the `downlevelIteration` before we published this package with this PR merged.  It should be something we can migrate away from before we remove the `forOf` (as anything using the current `@dojo/shim` can already down level emit the iteration).

**Comment by rorticus** [comment]
Yeah what @kitsonk said. Don't merge this 😛

**Comment by rorticus** [comment]
It looks like `for..of` is broken for multibyte strings, we might want to wait for that to be fixed before this is merged.

https://github.com/Microsoft/TypeScript/issues/17889

**Review by kitsonk — APPROVED** [review]

**Comment by kitsonk** [comment]
Discussion in Microsoft/TypeScript#17889 looks like TypeScript doesn't want to change their helper at this point in time.  I think this then ties this to dojo/cli-build-webpack#159 where we could provide our alternative helper as we load the `tslib` in `@dojo/shim`.

**Comment by kitsonk** [comment]
Also, this means #106 is included in this mix now.

**Comment by rorticus** [comment]
Closing this because it's going to get rolled up in #106

**Pull request closed without merging**
