### PR TITLE
Move global to /src and make CSP compatible

### LINKED ISSUE #61: Global cleanup
Per https://github.com/dojo/shim/pull/56#issuecomment-263655382 :

* There's a global implementation in shim and a different one in dojo/core. Should the one in core be removed and usage of it replaced with this one?
* What happens with this global implementation is csp prevents unsafe eval?

### PR DESCRIPTION
**Pull request by kitsonk**
**Type:** bug / feature

The following has been addressed in the PR:

* [X] There is a related issue
* [X] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [X] Unit or Functional tests are included in the PR

**Description:**

This adopts a CSP compliant global detection and migrates it from `src/support/global.ts` to `src/global.ts` because it is now aligning to the ES proposal for `global`.

Resolves #61

### CODE REVIEW

**Comment by agubler** [comment]
@kitsonk is this used by any downstream modules?

**Review by dylans — APPROVED** [review]

**Comment by agubler** [comment]
This is fine if there are no existing uses of support/global otherwise it will not be backwards compatible.

**Comment by kitsonk** [comment]
> is this used by any downstream modules?

Nothing depended upon it explicitly, so this is additive.  Remove of it from core thought (dojo/core#303) will cause some breakage.  Maybe we should alias that for now until we can clean it up everywhere else.

**Comment by kitsonk** [comment]
Also, it is slightly annoying me that we aren't testing the web worker code path too... we should really do that.

**Comment by dylans** [comment]
Same note to revisit this one as well @kitsonk , thanks!

**Comment by kitsonk** [comment]
Right now it is too difficult to test the web worker path and then collect the coverage information.  We don't really have a choice but to accept the untested code.

**Pull request merged**
