### PR TITLE
Remove node_modules cache from .travis.yml, upgrade intern, and remov…

### PR DESCRIPTION
**Pull request by jdonaghue**
**Type:** bug

**Description:** 

Remove node_modules cache from .travis.yml, upgrade intern, and remove typings

**Related Issue:** https://github.com/dojo/dojo2-package-template/issues/75

Please review this checklist before submitting your PR:

* [x] There is a related issue
* [x] All contributors have signed a CLA
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] The code passes the CI tests
* [x] Unit or Functional tests are included in the PR
* [x] The PR increases or maintains the overall unit test coverage percentage
* [x] The code is ready to be merged

### CODE REVIEW

**Comment by agubler** [comment]
@jdonaghue There are conflicts that need to be resolved.

**Comment by agubler** [comment]
@jdonaghue bump

**Comment by jdonaghue** [comment]
This appears to have auto merged. I did not explicitly merge it

**Comment by dylans** [comment]
No, jdonaghue:issue-75 was force-pushed and the commit history is gone... not sure what happened but I think the issue is in your repo...

**Pull request closed without merging**
